### ISSUE TITLE
impatient.nvim included twice

### ISSUE THREAD

**Issue by mwcz** [n0ks/dotfiles#1]
And the first one looks like a typo. :)  I just came across this searching for repos across github that are using impatient.

First:

https://github.com/n0ks/dotfiles/blob/14b2917030b02b0659f59485dd4ed1e3b46317ae/nvim/.config/nvim/init.vim#L6

Second:

https://github.com/n0ks/dotfiles/blob/14b2917030b02b0659f59485dd4ed1e3b46317ae/nvim/.config/nvim/init.vim#L63

**Comment by n0ks** [comment]
Didn't even see that.
I'll fix that typo today :)
